"use client";
import Link from "next/link";
import {useState} from "react";
type Product={title:string;price:string;description:string;image?:string;source:string};
type Creative={angle:string;hook:string;script:string;cta:string;shots:string[]};
const angles=["السعر والعرض","فاخر وفخامة","هدية ومناسبات","مشكلة ← حل","تجربة مستخدم UGC","فضول وتشويق"];
export default function Campaign(){
 const [url,setUrl]=useState("");const [loading,setLoading]=useState(false);const [brainLoading,setBrainLoading]=useState(false);const [error,setError]=useState("");const [product,setProduct]=useState<Product|null>(null);const [selected,setSelected]=useState<number[]>([0,1,4]);const [creatives,setCreatives]=useState<Creative[]>([]);
 async function analyze(){setError("");setCreatives([]);if(!url.trim()){setError("ألصق رابط المنتج أولاً.");return}setLoading(true);try{const r=await fetch("/api/analyze-product",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({url})});const d=await r.json();if(!r.ok)throw new Error(d.error||"تعذر تحليل المنتج");setProduct(d.product)}catch(e:any){setError(e.message||"حدث خطأ")}finally{setLoading(false)}}
 async function generate(){if(!product||!selected.length)return;setBrainLoading(true);setError("");try{const r=await fetch("/api/creative-brain",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({product,angles:selected.map(i=>angles[i])})});const d=await r.json();if(!r.ok)throw new Error(d.error||"تعذر إنشاء الأفكار");setCreatives(d.creatives)}catch(e:any){setError(e.message||"حدث خطأ")}finally{setBrainLoading(false)}}
 function toggle(i:number){setSelected(s=>s.includes(i)?s.filter(x=>x!==i):[...s,i])}
 return <div className="dash"><aside className="side"><div className="brand">إعلاني AI</div><br/><Link href="/dashboard">⌂ الرئيسية</Link><Link className="active" href="/campaign/new">✦ إنشاء حملة</Link></aside><main className="main"><div className="wizard"><h1>إنشاء حملة جديدة</h1><p>المنتج ← الزوايا ← <b>Saudi Creative Brain</b> ← الفيديو</p>
 <div className="card analyzer"><h2>🔗 ألصق رابط المنتج</h2><div className="urlbox campaignUrl"><input value={url} onChange={e=>setUrl(e.target.value)} placeholder="https://store.com/product/..."/><button className="primary btn" onClick={analyze} disabled={loading}>{loading?"جاري التحليل...":"تحليل المنتج"}</button></div>{error&&<p className="error">{error}</p>}</div>
 {product&&<><div className="card productPreview">{product.image?<img src={product.image} alt={product.title}/>:<div className="productimg">📦</div>}<div><span className="pill">{product.source}</span><h2>{product.title}</h2><div className="price small">{product.price||"السعر غير ظاهر"}</div><p>{product.description}</p></div></div>
 <h2>اختر الزوايا الإعلانية</h2><div className="angles">{angles.map((x,i)=><button onClick={()=>toggle(i)} className={"angle "+(selected.includes(i)?"selected":"")} key={x}><h3>{["💰","✨","🎁","🔥","👤","❓"][i]} {x}</h3><p>Hook سعودي مخصص لهذا المنتج</p></button>)}</div><br/><button className="primary btn" onClick={generate} disabled={brainLoading||!selected.length}>{brainLoading?"الذكاء الاصطناعي يكتب الحملة...":`✦ أنشئ ${selected.length} أفكار إعلانية`}</button></>}
 {creatives.length>0&&<section className="brainResults"><h2>🧠 الحملة المقترحة</h2><p>كل زاوية فيها Hook + Script + CTA + Shot list.</p>{creatives.map((c,i)=><div className="card creativeCard" key={i}><div className="creativeHead"><span className="pill">إعلان {i+1}</span><h3>{c.angle}</h3></div><h4>⚡ Hook</h4><div className="copybox">{c.hook}</div><h4>🎙️ النص السعودي</h4><p>{c.script}</p><h4>🎬 Shot list</h4><ol>{c.shots.map((s,j)=><li key={j}>{s}</li>)}</ol><h4>CTA</h4><div className="copybox">{c.cta}</div></div>)}<Link className="primary btn" href="/results">التالي: تحويل الأفكار إلى فيديو ←</Link></section>}</div></main></div>
}